add theme mdx
allenai/varnish-legacy pull request #312
Opened 2020-10-16 04:51 UTC by jonborchardt

this needs a bit of work to cleanup the `typeof Color` crap
but the pr is ready for review

2020-10-16 16:31 UTC, codeviking commented on demo/src/App.tsx
> +                    </Theme.Provider>
I like this new thing we're doing!

2020-10-16 16:46 UTC, codeviking commented on demo/src/pages/Colors/ColorValues.tsx
> +    color: typeof Color;
Isn't each `Color` an instance of a `Color` or something like that? Could we just export the type and use that instead, instead of sprinkling `typeof Color` throughout?

2020-10-16 17:04 UTC, codeviking commented on demo/src/pages/Colors/ColorValues.tsx
> +    colors: typeof Color[];
Is this the `typeof` of `Color[]`, or `(typeof Color)[]`? Maybe parens aren't required, but they might make it more clear.

You could also make a local type, like so:

```
type ColorInstance = typeof Color;
```

That said I'd just import the local type and use it here.

2020-10-16 17:05 UTC, codeviking commented on demo/src/pages/Palette/PaletteValues.tsx
> +                    ([key, color]: [string, any]) => {
Why `ant`? Could we use a TypeScript type-guard here instead?

2020-10-16 17:07 UTC, codeviking commented on demo/src/pages/Theme/page.mdx
> +The default Varnish theme, which provides programmatic access to the default values for colors, typography and other properties related to the user interface.
```suggestion
The default Varnish theme provides programmatic access to AI2 branded colors, typography and other properties related to the user interface. Using these values helps ensure your application's look and feel matches that of other AI2 applications.
```

2020-10-16 17:10 UTC, codeviking commented on demo/src/pages/Theme/page.mdx
> +Theme Provider for Varnish Theming.
Ah, so this isn't the actual context object, but rather an implementation of it, right?

I like the idea of switching to just be called `<VarnishApp>` or `<Varnish>`. Then it can safely act as a generic top-level thing that "activates" Varnish.  This way the user isn't confused by the `Provider` nomenclature, which doesn't make sense unless they're familiar with React.

I also notice that people rarely:

1. Override the theme.
2. Use the `Theme.Consumer`, instead they just import the default theme and use it instead.

So that might influence what we do here...

2020-10-16 17:11 UTC, codeviking commented on demo/src/pages/Theme/page.mdx
> +<ThemeValues />
We should include a doc for how to use the theme programmatically. I've been asked that 3x times in the last 2 weeks.

I'd suggest we just document how to import and use `Theme.default`, instead of referencing the whole `Theme.Consumer` mechanism. You could include an "Advanced" section where you cover how to override the theme and use `Theme.Consumer` to access the overriden values...this seems like it'd be good to have penciled down so it's easy for a user to do if/when they want to.

2020-10-16 17:12 UTC, codeviking commented on theme/index.ts
> +const Theme = JSON.parse(JSON.stringify(ThemeImpl)); // any is so we can add the random statics below
Wait, why are we serializing and then deserializing this? This is somewhat expensive to do, and we'll be doing it every time someone loads a page. There's got to be a better way to do this...

2020-10-16 17:14 UTC, codeviking requested changes
I think there's some missing docs and some work to put into thinking about how people access the theme now.

I also don't think we should serialize and then immediately parse the theme. We need to find a better way to do that that isn't a performance hit. Let's chat about why we're doing that.

2020-10-16 17:21 UTC, codeviking commented on theme/index.ts
> +const Theme = JSON.parse(JSON.stringify(ThemeImpl)); // any is so we can add the random statics below
We chatted, this is to prevent mutation of the original, we can use `Object.assign` or the merge / spread operator instead: `...`

2020-10-16 17:24 UTC, codeviking approved these changes
LGTM; We chatted and:

* We can use `Object.assign({}, ThemeImpl)` to prevent mutating the original reference.
* We're going to dig into why `Theme.Color` isn't what we expect.
* We're going to migrate `Theme.Provider` to a top-level, generic `Varnish` element, but we don't *have* to do that for this to land.

👍

2020-10-19 19:02 UTC, jonborchardt commented on demo/src/AppChrome.tsx
> +            <Layout bgcolor="white">
the only change in this file is removing ln 63

2020-10-19 19:29 UTC, jonborchardt commented on demo/src/pages/Colors/ColorValues.tsx
> +    color: typeof Color;
fixed, not needing typeof now

2020-10-19 19:30 UTC, jonborchardt commented on demo/src/pages/Theme/page.mdx
> +Theme Provider for Varnish Theming.
Added VarnishApp

2020-10-19 19:30 UTC, jonborchardt commented on demo/src/pages/Theme/page.mdx
> +<ThemeValues />
done... but Theme.default is now just Theme

2020-10-19 19:30 UTC, jonborchardt commented on theme/index.ts
> +const Theme = JSON.parse(JSON.stringify(ThemeImpl)); // any is so we can add the random statics below
fixed

2020-10-19 20:25 UTC, codeviking commented on README.md
> +       ReactDOM.render(<App />, document.getElementById('root'));
👍  This is great.

2020-10-19 20:26 UTC, codeviking commented on README.md
> +            <VarnishApp layoutVariant="app">
```suggestion
            <VarnishApp layoutVariant="left-aligned">
```

I've never understood what `app` means. It's a little too generic for my taste. They're all applications, after all :).

2020-10-19 20:26 UTC, codeviking commented on components/VarnishApp.tsx
> +        <DefaultLayoutProvider layoutVariant={props.layoutVariant}>
```suggestion
        <DefaultLayoutProvider layoutVariant={props.layoutVariant || "default"}>
```

2020-10-19 20:26 UTC, codeviking commented on components/VarnishApp.tsx
> +    layoutVariant: LayoutVariant;
```suggestion
    layoutVariant?: LayoutVariant;
```

2020-10-19 20:27 UTC, codeviking commented on components/VarnishApp.tsx
> +        <DefaultLayoutProvider layoutVariant={props.layoutVariant}>
I think we should support them not providing a value -- and do the right thing by default (which is probably a center-aligned layout).

2020-10-19 20:29 UTC, codeviking commented on demo/src/pages/Theme/page.mdx
> +<ThemeValues />
Nice !I like that more.

2020-10-19 20:30 UTC, codeviking commented on demo/src/pages/Theme/page.mdx
> +console.log(redSix.hex)
If you use red 5 it could be a star wars reference in disguise...

// Red 5 standing by...
const redFiveStandingBy = Theme.color.R5;
```

2020-10-19 20:31 UTC, codeviking commented on demo/src/pages/VarnishApp/page.mdx
> +context.
```suggestion
All applications need to be wrapped in a `<VarnishApp>`. This ensures Varnish is setup correctly. If you don't do this your application probably won't compile, or if it does things probably won't work quite right.
```

2020-10-19 20:32 UTC, codeviking commented on demo/src/pages/VarnishApp/page.mdx
> +context.
I'd leave it more general, we might do more :).

2020-10-19 20:33 UTC, codeviking commented on demo/src/pages/VarnishApp/page.mdx
> +| layoutVariant | Defines if the header and footer are left or center justified | 'app' \| 'hcenter' | 'hcenter' |
```suggestion
| layoutVariant | Changes the top level layout, which right now only impacts the horizontal alignment of your application. | 'app' \| 'hcenter' | 'hcenter' |
```

2020-10-19 20:40 UTC, codeviking commented on theme/index.ts
> +export type VarnishTheme = typeof ThemeImpl;
```suggestion
import { Theme } from './Theme';

export {
   Provider: ThemeProvider,
   RGB,
   Color,
   ...Theme
}
```

I think you can do ☝️  to avoid the `any` n' all that.

2020-10-19 20:41 UTC, codeviking approved these changes
LGTM; Left a few ideas.

2020-10-19 20:54 UTC, jonborchardt commented on README.md
> +            <VarnishApp layoutVariant="app">
later (soon) it will go away...

2020-10-19 21:44 UTC, jonborchardt commented on README.md
> +            <VarnishApp layoutVariant="app">
renamed

2020-10-19 21:45 UTC, jonborchardt commented on components/VarnishApp.tsx
> +        <DefaultLayoutProvider layoutVariant={props.layoutVariant}>
done

2020-10-19 21:45 UTC, jonborchardt commented on components/VarnishApp.tsx
> +    layoutVariant: LayoutVariant;
done

2020-10-19 21:45 UTC, jonborchardt commented on demo/src/pages/Theme/page.mdx
> +console.log(redSix.hex)
nice, done

2020-10-19 21:45 UTC, jonborchardt commented on demo/src/pages/VarnishApp/page.mdx
> +context.
done

2020-10-19 21:45 UTC, jonborchardt commented on demo/src/pages/VarnishApp/page.mdx
> +| layoutVariant | Defines if the header and footer are left or center justified | 'app' \| 'hcenter' | 'hcenter' |
done

2020-10-19 21:45 UTC, jonborchardt commented on theme/index.ts
> +export type VarnishTheme = typeof ThemeImpl;
done

2020-10-19 21:45 UTC, merged